version: '3'

services:
  frontend:
    image: ma1gus/time-app-frontend-dev
    ports:
      - 3000:3000
    restart: always
  api:
    image: ma1gus/time-app-api-dev
    ports:
      - 5555:5000
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PORT: '3306'
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: time_db
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: time_db
    restart: always
    volumes:
      - mysql_data_pub:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - 8888:8080
    restart: always

volumes:
  mysql_data_pub: